package google.bit;

/**
 * Created by yingtan on 8/8/17.
 *
 * 389. Find the Difference
 DescriptionHintsSubmissionsDiscussSolution
 Discuss Pick One
 Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.

 //sol:
 // 0 XOR char = char
 // if s t both have a, then a ^ a = 0
 // so the left one must be the extra char
 */
public class FindDifference {
    public char findTheDifference(String s, String t) {
        //sol:
        // 0 XOR char = char
        // if s t both have a, then a ^ a = 0
        // so the left one must be the extra char
        char c = 0;
        for (int i = 0; i < s.length(); ++i) {
            c ^= s.charAt(i);
        }
        for (int i = 0; i < t.length(); ++i) {
            c ^= t.charAt(i);
        }
        return c;
    }
}
